# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-dev*'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get latest SHA of pypa/gh-action-pypi-publish
        id: get_sha
        run: |
          ACTION_SHA=$(curl -s https://api.github.com/repos/pypa/gh-action-pypi-publish/commits/main | jq -r '.sha')
          echo "ACTION_SHA=$ACTION_SHA" >> $GITHUB_ENV

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@${{ env.ACTION_SHA }}
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}